-- MySQL Script generated by MySQL Workbench
-- Tue Mar 14 16:57:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `surname` VARCHAR(60) NOT NULL,
  `datebirthday` DATETIME NOT NULL,
  `document` VARCHAR(14) NOT NULL,
  `email` VARCHAR(140) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `datecreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` VARCHAR(1) NOT NULL,
  `deviceToken` VARCHAR(255) NULL,
  `Country` VARCHAR(50) NOT NULL,
  `dateUpdated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `document_UNIQUE` (`document` ASC) VISIBLE,
  UNIQUE INDEX `deviceToken_UNIQUE` (`deviceToken` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`tb_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `dtCreated` DATETIME DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_userpermission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_userpermission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUsers` INT NOT NULL,
  `idPermissions` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_userpermission_tb_users_idx` (`idUsers` ASC) VISIBLE,
  INDEX `fk_tb_userpermission_tb_permissions1_idx` (`idPermissions` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_userpermission_tb_users`
    FOREIGN KEY (`idUsers`)
    REFERENCES `mydb`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_userpermission_tb_permissions1`
    FOREIGN KEY (`idPermissions`)
    REFERENCES `mydb`.`tb_permissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`loja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imageUrl` VARCHAR(255) NULL,
  `latitude` VARCHAR(45) NOT NULL,
  `longitude` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `lojacol` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(150) NULL,
  `dtCreated` DATETIME DEFAULT now(),
  `idUsers` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC),
  INDEX `fk_loja_tb_users1_idx` (`idUsers` ASC) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_loja_tb_users1`
    FOREIGN KEY (`idUsers`)
    REFERENCES `mydb`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  `name` VARCHAR(45) NOT NULL,
  `dtCreated` DATETIME DEFAULT now(),
  `dtModifies` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `price` DOUBLE NOT NULL,
  `dateCreated` DATETIME DEFAULT now(),
  `dateModificated` DATETIME NOT NULL,
  `idCategory` INT NOT NULL,
  `idLoja` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_products_tb_category1_idx` (`idCategory` ASC) VISIBLE,
  INDEX `fk_tb_products_loja1_idx` (`idLoja` ASC) VISIBLE,
  CONSTRAINT `fk_tb_products_tb_category1`
    FOREIGN KEY (`idCategory`)
    REFERENCES `mydb`.`tb_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_products_loja1`
    FOREIGN KEY (`idLoja`)
    REFERENCES `mydb`.`loja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_vendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(1) NULL,
  `dateCreated` DATETIME DEFAULT now(),
  `dateModify` DATETIME NULL,
  `idProducts` INT NOT NULL,
  `tb_users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_vendas_tb_products1_idx` (`idProducts` ASC) VISIBLE,
  INDEX `fk_tb_vendas_tb_users1_idx` (`tb_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_vendas_tb_products1`
    FOREIGN KEY (`idProducts`)
    REFERENCES `mydb`.`tb_products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_vendas_tb_users1`
    FOREIGN KEY (`tb_users_id`)
    REFERENCES `mydb`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_pushs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_pushs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `idUsers` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `dateSend` DATETIME DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `fk_tb_pushs_tb_users1_idx` (`idUsers` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pushs_tb_users1`
    FOREIGN KEY (`idUsers`)
    REFERENCES `mydb`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
